package com.matrixlab.focustime.filter

/**
 * Static block-lists for content filtering.
 * All sets use HashSet for O(1) lookup.
 */
object BlockLists {

    /** Known pornographic app package names. */
    val pornAppPackages: Set<String> = hashSetOf(
        "com.pornhub.android",
        "com.xvideos.app",
        "com.xnxx.app",
        "com.redtube.app",
        "com.youporn.app",
        "com.tube8.app",
        "com.spankbang.app",
        "com.brazzers.app",
        "com.naughtyamerica.app",
        "com.realitykings.app",
        "com.bangbros.app",
        "com.onlyfans.app",
        "com.fansly.app",
        "com.stripchat.app",
        "com.chaturbate.app",
        "com.livejasmin.app",
        "com.cam4.app",
        "com.bongacams.app",
        "com.myfreecams.app",
        "com.eporner.app",
        "com.tnaflix.app",
        "com.hclips.app",
        "com.txxx.app",
        "com.porntrex.app",
        "com.fuq.app"
    )

    /** Known browser package names. */
    val browserPackages: Set<String> = hashSetOf(
        "com.android.chrome",
        "com.chrome.beta",
        "com.chrome.dev",
        "com.chrome.canary",
        "org.mozilla.firefox",
        "org.mozilla.firefox_beta",
        "org.mozilla.fenix",
        "org.mozilla.focus",
        "com.microsoft.emmx",
        "com.opera.browser",
        "com.opera.mini.native",
        "com.opera.gx",
        "com.brave.browser",
        "com.sec.android.app.sbrowser",
        "com.sec.android.app.sbrowser.beta",
        "com.UCMobile.intl",
        "com.kiwibrowser.browser",
        "com.vivaldi.browser",
        "com.duckduckgo.mobile.android",
        "org.chromium.webview_shell",
        "com.mi.globalbrowser",
        "com.huawei.browser",
        "mark.via.gp",
        "org.torproject.torbrowser"
    )

    /** Known adult domains (without www. prefix). */
    val pornDomains: Set<String> = hashSetOf(
        "pornhub.com",
        "xvideos.com",
        "xnxx.com",
        "xhamster.com",
        "redtube.com",
        "youporn.com",
        "tube8.com",
        "spankbang.com",
        "eporner.com",
        "tnaflix.com",
        "hclips.com",
        "txxx.com",
        "porntrex.com",
        "fuq.com",
        "beeg.com",
        "drtuber.com",
        "sunporno.com",
        "empflix.com",
        "4tube.com",
        "pornone.com",
        "3movs.com",
        "fapvid.com",
        "alohatube.com",
        "porndig.com",
        "gotporn.com",
        "anyporn.com",
        "tubegalore.com",
        "updatetube.com",
        "proporn.com",
        "dansmovies.com",
        "porngo.com",
        "porn.com",
        "porn300.com",
        "thumbzilla.com",
        "pornpics.com",
        "xxxbunker.com",
        "hqporner.com",
        "daftsex.com",
        "sxyprn.com",
        "nudevista.com",
        "ixxx.com",
        "lobstertube.com",
        "fapcat.com",
        "fux.com",
        "porntube.com",
        "4porn.com",
        "bellesa.co",
        "brazzers.com",
        "naughtyamerica.com",
        "realitykings.com",
        "bangbros.com",
        "mofos.com",
        "digitalplayground.com",
        "babes.com",
        "twistys.com",
        "wicked.com",
        "adulttime.com",
        "vixen.com",
        "blacked.com",
        "tushy.com",
        "deeper.com",
        "onlyfans.com",
        "fansly.com",
        "manyvids.com",
        "clips4sale.com",
        "iwara.tv",
        "rule34.xxx",
        "e-hentai.org",
        "nhentai.net",
        "nhentai.to",
        "hanime.tv",
        "hentaihaven.xxx",
        "hentai.tv",
        "gelbooru.com",
        "danbooru.donmai.us",
        "sankakucomplex.com",
        "hitomi.la",
        "exhentai.org",
        "fakku.net",
        "tsumino.com",
        "simply-hentai.com",
        "stripchat.com",
        "chaturbate.com",
        "livejasmin.com",
        "cam4.com",
        "bongacams.com",
        "myfreecams.com",
        "camsoda.com",
        "flirt4free.com",
        "streamate.com",
        "imlive.com",
        "jerkmate.com",
        "literotica.com",
        "sexstories.com",
        "asstr.org",
        "imagefap.com",
        "motherless.com",
        "heavy-r.com",
        "efukt.com",
        "bestgore.fun",
        "theporndude.com",
        "mrdeepfakes.com",
        "coomer.su",
        "kemono.su",
        "simpcity.su",
        "bunkr.si",
        "thisvid.com",
        "toroporno.com",
        "voyeurhit.com",
        "rec-tube.com",
        "crazysht.com"
    )

    /**
     * Strong-signal keywords. Each keyword is specific enough to adult content
     * that a single occurrence in a URL or page title warrants blocking.
     * All entries must be lowercase.
     */
    val explicitKeywords: List<String> = listOf(
        "pornhub",
        "xvideos",
        "xhamster",
        "redtube",
        "youporn",
        "xnxx",
        "brazzers",
        "bangbros",
        "onlyfans.com",
        "chaturbate",
        "stripchat",
        "livejasmin",
        "hentai",
        "nhentai",
        "rule34",
        "e-hentai",
        "milf",
        "creampie",
        "gangbang",
        "deepthroat",
        "blowjob",
        "handjob",
        "threesome",
        "anal sex",
        "hardcore porn",
        "lesbian porn",
        "gay porn",
        "porn video",
        "xxx video",
        "sex video",
        "nude video",
        "naked video",
        "pussy",
        "cock",
        "dildo",
        "orgasm",
        "cumshot",
        "squirt",
        "bondage porn",
        "bdsm porn",
        "escort service",
        "cam girl",
        "camgirl",
        "webcam sex",
        "live sex",
        "adult video",
        "jerkmate",
        "fapcat",
        "spankbang"
    )

    /** URL-bar view-IDs for popular browsers, used to locate the address field. */
    val browserUrlBarIds: List<String> = listOf(
        "com.android.chrome:id/url_bar",
        "com.android.chrome:id/search_box_text",
        "com.chrome.beta:id/url_bar",
        "com.chrome.dev:id/url_bar",
        "com.chrome.canary:id/url_bar",
        "org.mozilla.firefox:id/mozac_browser_toolbar_url_view",
        "org.mozilla.firefox_beta:id/mozac_browser_toolbar_url_view",
        "org.mozilla.fenix:id/mozac_browser_toolbar_url_view",
        "org.mozilla.focus:id/mozac_browser_toolbar_url_view",
        "com.microsoft.emmx:id/url_bar",
        "com.opera.browser:id/url_field",
        "com.opera.mini.native:id/url_field",
        "com.brave.browser:id/url_bar",
        "com.sec.android.app.sbrowser:id/location_bar_edit_text",
        "com.UCMobile.intl:id/address_editor_with_progress",
        "com.kiwibrowser.browser:id/url_bar",
        "com.vivaldi.browser:id/url_bar",
        "com.duckduckgo.mobile.android:id/omnibarTextInput",
        "com.mi.globalbrowser:id/url_bar",
        "com.huawei.browser:id/url_bar",
        "mark.via.gp:id/am",
        "org.torproject.torbrowser:id/mozac_browser_toolbar_url_view"
    )
}
